beabee-communityrm/monorepo

apps/backend/package.json, packages/core/jest.config.js, packages/core/package.json, packages/core/src/data/options/defaults.ts, packages/core/src/lib/gocardless.ts, packages/core/src/lib/stripe.ts, packages/core/src/models/Contact.ts, packages/core/src/models/JoinForm.ts, packages/core/src/providers/email/SendGridProvider.ts, packages/core/src/providers/payment/GCProvider.ts, packages/core/src/providers/payment/StripeProvider.ts, packages/core/src/services/CalloutsService.ts, packages/core/src/services/ContactMfaService.ts, packages/core/src/services/ContactsService.ts, packages/core/src/services/GiftService.ts, packages/core/src/services/PaymentService.ts, packages/core/src/utils/auth.ts, packages/core/src/utils/payment.ts, yarn.lock
Add prettier and remove unused dependencies from backend
=> refactor: clean up core

apps/backend/jest.config.js, packages/core/jest.config.js, packages/core/tsconfig.test.json
Fix running tests that was broken by #30
=> build: fix build tests

apps/backend/src/api/transformers/BaseContactTransformer.ts, apps/frontend/src/components/pages/admin/contacts/contacts.interface.ts, apps/frontend/src/pages/admin/contacts/index.vue, packages/common/src/search/callouts.ts, packages/common/src/search/contacts.ts, packages/common/src/search/operators.ts, packages/common/src/utils/rules.ts
=> feat: filter by newsletter groups

apps/frontend/locales/de.json, apps/frontend/locales/de@easy.json, apps/frontend/locales/de@informal.json, apps/frontend/locales/en.json, apps/frontend/locales/it.json, apps/frontend/locales/nl.json, apps/frontend/locales/pt.json, apps/frontend/locales/ru.json, apps/frontend/src/components/forms/AppInput.vue, apps/frontend/src/components/forms/AppLinkList.vue, apps/frontend/src/components/forms/AppRepeatable.vue, apps/frontend/src/pages/admin/membership-builder/confirmation.vue
=> feat: add groups to membership builder

apps/frontend/src/components/form-builder/form-builder.css
Ported changes from https://github.com/beabee-communityrm/beabee-frontend/pull/603
=> feat: Form.IO builder style improvements

.github/workflows/backend-deploy.yml, .github/workflows/backend-release.yml, apps/frontend/package.json, package.json
Another GitHub Action error that only occurred in main and was therefore previously unnoticed similar to #55.
I have also moved the copying of the .env for the frontend to the package.json of the frontend, which should be clearer
=> chore(github): Fix action: Location of .env has changed

apps/backend/src/tools/database/import-callout-responses.ts, apps/backend/src/tools/database/import-steady.ts, packages/core/src/services/CalloutsService.ts
This tool allows you to batch upload callout responses to a callout from a CSV
```bash
node import-callout-responses <callout-slug> < <csvfile>
```
=> feat: import response tool

apps/frontend/src/pages/admin/membership-builder/confirmation.vue, packages/core/src/migrations/1731670066414-MigrateSegmentTagRules.ts
This removes tag segment rules with unused (and not existing) tags
=> Hotfix(feat/contact-tagging): Delete tag rules with with unused tags

apps/backend/package.json, apps/backend/src/api/dto/SignupFlowDto.ts, apps/backend/src/api/validators/IsVatNumber.ts, deno.lock, yarn.lock
Stripe rejects the VAT number if it's invalid, so check it before continuing the join flow so the user can get a better error message.
=> fix: check for valid VAT number

apps/frontend/public/embed.ts, apps/frontend/src/layouts/layout-Dashboard.vue, apps/frontend/src/pages/callouts/[id]/index.vue, apps/frontend/src/pages/callouts/[id]/thanks.vue
=> chore: embed block fixes for 0.23.x

apps/frontend/src/pages/callouts/[id]/map.vue
Add query parameters to track the zoom and center level. This is inline with what most map tools do (Google Maps, Bing, OpenStreetMap, etc.), it enables users to share particular positions on a map, and for our use case in particular enables admins to share links with the map positioned in a different place on page load.
=> feat: add query parameter for map center and zoom level

apps/frontend/src/lib/i18n.ts
Just a small PR to update the locale import path to ESM format
=> fix(i18n): update locale import path to ESM format

packages/locale/generate.ts, packages/locale/package.json
Generate locales for a branch, ported from #152
=> chore: generate locale from branch name

apps/frontend/src/pages/join/index.vue, packages/client/src/api/signup.client.ts
The signup flow showed an error, although the signup flow itself still worked (the user still received a confirm email email).
=> fix: no contribution signup error

apps/frontend/src/pages/admin/settings/theme.vue, packages/vue/src/plugins/theme.js
This fixes the issue where the contribution button for the payment process no longer works.
- Fixed theme plugin to use resolveConfig from Tailwind CSS for full configuration handling.
- Added AppRadioInput component to the admin settings page for improved functionality.
=> fix(vue/theme): Fix theme plugin

apps/frontend/src/components/pages/admin/callouts/tabs/SettingsTab.vue
Use the experimental features flag to toggle the callout/CRM connection (NL signup)
=> chore: CRM feature behind flag

packages/core/src/templates/email.ts
- Modified the email footer template to include the logo URL dynamically sourced from the configuration.
- This change enhances flexibility by allowing the logo URL to be easily updated in the config file.
=> fix(email): Update email footer to use dynamic logo URL from config

apps/backend-cli/src/commands/migrate-uploads.ts, packages/common/src/types/index.ts, packages/common/src/types/s3-metadata.ts, packages/core/src/services/DocumentService.ts, packages/core/src/services/ImageService.ts, packages/core/src/utils/file.ts
- Updated the `migrateUploadsCommand` to set a default source directory for uploads.
- Added a new `S3Metadata` interface to standardize metadata structure for S3/MinIO objects.
- Refactored `DocumentService` and `ImageService` to utilize the new `S3Metadata` interface for metadata handling.
- Improved the `sanitizeFilename` function to enhance filename sanitization and ensure compatibility with HTTP headers.
=> feat(upload-migration): Enhance upload migration command

.cursor/rules/frontend-code-structure.mdc, .cursor/rules/general-code-structure.mdc, .cursor/rules/migrate-vue-component.mdc, .cursor/rules/new-package-vanilla.mdc, .cursor/rules/new-vue-component.mdc, .cursor/rules/vue-component-story-documentation.mdc, .cursor/rules/vue-component-story.mdc, .cursor/rules/workspace-structure.mdc, .cursor/rules/yarn-commands.mdc, packages/vue/src/components/index.ts, packages/vue/src/components/template/AppTemplate.story.md, packages/vue/src/components/template/AppTemplate.story.vue, packages/vue/src/components/template/AppTemplate.vue, packages/vue/src/components/template/index.ts
This PR backports Cursor IDE rule improvements from PR #235 to enable faster review and merge. These enhancements significantly improve AI-assisted development workflows for Vue component creation and migration.
- **Enhanced existing rules**: Updated `frontend-code-structure.mdc` and `general-code-structure.mdc`
- **New specialized rules**:
- `migrate-vue-component.mdc` - Guidelines for migrating components from frontend to vue package
- `new-vue-component.mdc` - Best practices for creating new Vue components
- `vue-component-story.mdc` - Standards for component story creation
- `vue-component-story-documentation.mdc` - Documentation guidelines for stories
- `yarn-commands.mdc` - Workspace command reference
- Updated `workspace-structure.mdc` - Enhanced workspace documentation
- **New …
=> feat(cursor): Improve Cursor IDE rules and add Vue component template

apps/frontend/src/utils/url.ts, apps/legacy/src/app.ts, packages/common/src/utils/url.ts
- Moved image URL resolution to common utilities
- Wrapped it in frontend
- Used for favicon resolution in legacy app
Note this is a quick fix, I also have created a PR with a cleaner solution in #252
=> fix(favicon): Favicon image URL resolution

apps/e2e-api-tests/.prettierrc.mjs, apps/e2e-api-tests/package.json, apps/e2e-api-tests/src/tests/contact.test.ts, apps/e2e-api-tests/src/tests/content.test.ts, apps/e2e-api-tests/tsconfig.json, apps/e2e-api-tests/vitest.config.ts, yarn.lock
The first in a series of PRs to improve our E2E test configuration and then add some tests
=> test: add Prettier to e2e tests

packages/esbuild/src/locale/utils.ts, packages/locale/src/locales/de@easy.json, packages/locale/src/locales/el.json, packages/locale/src/locales/fr.json, packages/locale/src/locales/it.json, packages/locale/src/locales/nl.json, packages/locale/src/locales/pt.json, packages/locale/src/locales/ru.json, packages/locale/src/template.json
Make the locale build scripts deterministic by always sorting keys and add a EOF line break to match Weblate's output. Also added missing translations
=> fix: generate locale JSON files deterministically

apps/frontend/src/components/callout/CalloutReviewerManager.vue, apps/frontend/src/components/callout/CalloutReviewerSearch.vue, packages/locale/src/locales/de.json, packages/locale/src/locales/de@easy.json, packages/locale/src/locales/de@informal.json, packages/locale/src/locales/el.json, packages/locale/src/locales/en.json, packages/locale/src/locales/fr.json, packages/locale/src/locales/it.json, packages/locale/src/locales/nl.json, packages/locale/src/locales/pt.json, packages/locale/src/locales/ru.json, packages/locale/src/template.json
This PR adds adding callout reviewers via email including notification messages.
=> feat: add search by email callout reviewer

apps/router/nginx.conf
This PR includes redirection of all urls from callout > crowdnewsroom. (I am not sure if this is sufficient)
=> feat: redirect links from callout > crowdnewsroom

apps/router/nginx.conf
This adjust the redirection to legacy app
=> fix(router): redirection to legacy app
