beabee-communityrm/monorepo

- .dockerignore
- apps/backend/.dockerignore
- apps/backend/Dockerfile
- apps/frontend/.dockerignore
- apps/frontend/Dockerfile
- apps/frontend/vite.config.ts
This is my attempt to understand and simplify the new Docker builds in the monorepo. It also fixes the problem that the `.dockerignore` files were being ignored (haha), as it needs to be in the root of the context.
Mostly it reduces the number of lines needed to add the common package and removes as much context specific knowledge as possible.
> build: simplify Docker builds

- apps/backend/src/webhooks/handlers/gocardless.ts
Tell GoCardless something has failed so that it retries the webhooks later.
> fix: send 500 when there is an internal error

- apps/backend/src/api/controllers/ContentController.ts
- apps/backend/src/webhooks/handlers/stripe.ts
- apps/frontend/src/pages/admin/settings/index.vue
- packages/core/src/data/options/defaults.ts
- packages/core/src/lib/stripe.ts
- packages/core/src/services/GiftService.ts
- packages/core/src/type/index.ts
- packages/core/src/type/stripe-tax-rate-create-params.ts
Enable sales tax. For simplicity, this PR makes the Stripe tax rate code a bit less generic so it only deals with sales tax stuff.
Instead of batch updating all the subscriptions in one go, just update them when they create their next invoice. This avoids needing any sort of batch job management. It uses the `invoice.created` webhook to update the draft invoice, and also update the subscription.
This PR also improves the documentation a bit by formatting some comments into JSDoc
> feat: enable Sales tax 

- apps/backend/src/api/controllers/ContactController.ts
- packages/core/src/services/PaymentFlowService.ts
Fix a bug where a join flow object is not deleted if the join flow has no contribution.
> fix: always complete join flow, even if no contribution

- .github/actions/setup/action.yml
- .github/workflows/common-check.yml
Deno v2 is released but we are using v1 so far. For v2 we need a separate PR.
This is a simper version of #54.
> chore(github): Set deno to v1.x for Github Actions

- apps/frontend/src/components/pages/admin/callouts/steps/ContentStep.vue
- apps/frontend/src/pages/callouts/[id]/index.vue
Allow callouts to be prefilled from a query parameter, e.g.
```
https://my.beabee.io/callouts/my-favourite-color/respond?answers={"slide1": {"color": "red}}
```
`answers` should be a valid `CalloutResponseAnswersSlide`, or it's ignored. To help advanced users create the correct JSON object the slide ID is now shown on the form editor in advanced mode.
> feat: support simple prefilled answer query parameter

- packages/core/src/migrations/1729522899474-RemoveResponseIsPartialFlag.ts
- packages/core/src/models/CalloutResponse.ts
- packages/core/src/services/CalloutsService.ts
Remove the unused `isPartial` flag. This was used in the legacy frontend to save partial answers, it was never ported over to the new frontend and has never been used by any clients (except the Cable).
> chore: remove deprecated isPartial flag

- apps/backend/Dockerfile
- apps/backend/crontab
This PR fixes the cron job service, which had the following problems
1. No env vars passed to the cron jobs
2. `node` couldn't be found in cronjobs (needs modified `PATH`)
3. Logs were going to the default cron log location (/var/mail) rather than stdout
To make cron jobs work properly we need to
1. Store the environment variables in `/etc/environment`
2. Add `/usr/local/bin` to the `PATH`
3. Install rsyslog and redirect cron logs to `/proc/1/fd/1`. This is stdout for the main process (PID 1).
> fix: cron job service

- apps/frontend/src/components/form-renderer/form-renderer.css
The formatting for some inputs is broken, only textareas need to respect whitespace.
Before:
After
> fix: only add whitespace pre-wrap to text areas

- packages/core/src/migrations/1731670066414-MigrateSegmentTagRules.ts
Adds a handwritten migration to convert tag names to UUIDs in segment rules. The issue was reproduced locally with test data and the migration was verified to work correctly. I noticed this problem in the demo instance.
* Added new migration `1731670066414-MigrateSegmentTagRules.ts` to handle tag name to UUID conversion
* Includes both up and down migrations for reversibility
* Handles nested rule groups
* Provides detailed logging during migration process
* Reproduced the issue locally with segments using tag names
* Verified migration successfully converts tag names to corresponding UUIDs
* Confirmed segment filtering works correctly after migration
I also tested it on the demo instance and it works there too. To do that, I merged these changes into dev and temporarily switched the demo …
> hotfix(segments): Segment Tag Rules Migration

- apps/backend/src/api/transformers/TagTransformer.ts
Fixes an issue where the tag filter operators were swapped in the `TagTransformer`, causing incorrect results when filtering contacts by tag presence. The logic of is_empty and is_not_empty was reversed.
- Fixed operator logic in `tagFilterHandler`
- "is_empty" now correctly shows contacts without tags
- "is_not_empty" now correctly shows contacts with tags
Verified that:
- Filtering for contacts with tags shows correct results
- Filtering for contacts without tags shows correct results
- Specific tag filtering remains unaffected
> fix(contact-tagging): Fix Tag Filter Logic

- apps/backend/src/api/dto/CalloutResponseDto.ts
- apps/backend/src/api/transformers/BaseCalloutResponseTransformer.ts
- apps/backend/src/api/transformers/CalloutResponseExporter.ts
- apps/backend/src/api/transformers/CalloutResponseMapTransformer.ts
- apps/backend/src/api/transformers/CalloutResponseTransformer.ts
- Only reviewers and admins can export for now to prevent data leaks
- Only reviewers and admins can see response assignees
> chore: callout response entity permission changes

- packages/prettier-config/index.mjs
I don't really know why, it might be related to https://github.com/prettier/prettier-vscode/issues/3066, but my Prettier stopped working in VSCode . It was working fine on the command line, e.g. `yarn prettier -c .`. The console in VSCode just reported "Invalid configuration".
A frustrating amount of debugging later, the change in this PR seems to fix it :shrug:.
> fix: prettier formatting in VSCode

- packages/tsconfig/tsconfig.server.json
When running `yarn dev`, the terminal output is being cleared on building the backend, which makes it difficult to debug or monitor the build process.
This PR modifies the build script to prevent the terminal output from being cleared when running `yarn dev`.
- Updated the `packages/tsconfig/tsconfig.server.json` by adding `"preserveWatchOutput": true`
- Run `yarn dev` and verify that the terminal output is no longer cleared.
> Prevent terminal output from being cleared on `yarn dev`

- apps/frontend/locales/de.json
- apps/frontend/locales/de@easy.json
- apps/frontend/locales/de@informal.json
- apps/frontend/locales/en.json
- apps/frontend/locales/it.json
- apps/frontend/locales/nl.json
- apps/frontend/locales/pt.json
- apps/frontend/locales/ru.json
- apps/frontend/src/components/payment-method/PaymentMethodIcon.vue
- apps/frontend/src/components/payment-method/icons/iDEAL.vue
- packages/common/src/data/payment-method.ts
- packages/common/src/utils/payments.ts
- packages/core/src/lib/stripe.ts
- packages/core/src/providers/payment-flow/StripeProvider.ts
- packages/core/src/services/PaymentFlowService.ts
- packages/core/src/services/PaymentService.ts
Support the iDEAL payment method. This method is slightly more complicated than others because you need to convert it to a SEPA direct debit during the setup process.
More details here: https://docs.stripe.com/payments/ideal/set-up-payment
> feat: add support for iDEAL payments

- packages/core/src/services/ContactsService.ts
- packages/core/src/services/NewsletterService.ts
- packages/core/src/type/contact-newsletter-updates.ts
This PR makes the behaviour of `NewsletterService.upsertContact` consistent so its source of truth for a contact is always the object itself. Before there was an ambiguity between whether the contact should be passed to this method before or after having being update. Now it should always happen after the contact update, making the interaction between `ContactService` and `NewsletterService` much clearer.
It also removes the `shouldUpdate` guard, which in practice didn't prevent many (if any) updates, and also reduces the separation of concerns between the `ContactService` and `NewsletterService`.
> refactor: clearer data update order for Mailchimp

- packages/core/src/data/options/defaults.ts
- packages/core/src/lib/mailchimp.ts
- packages/core/src/providers/newsletter/MailchimpProvider.ts
- packages/core/src/providers/newsletter/NoneProvider.ts
- packages/core/src/services/NewsletterService.ts
- packages/core/src/type/newsletter-provider.ts
- packages/core/src/type/update-newsletter-contact.ts
Add a flag to the newsletter provider that tells admins if the user is an active user on beabee. At the moment we use whether or not they've set a password as a proxy for this.
> feat: add active user tag to Mailchimp

- apps/webhooks/src/handlers/mailchimp.ts
Removes a now unnecessary active member tag check. This was made redundant by #124, as the `NewsletterService` and providers now always handles this internally.
> Remove unnecessary add tag, now handled inside NewsletterService

- apps/backend/src/api/dto/ContactTagDto.ts
- apps/backend/src/api/interceptors/ValidateResponseInterceptor.ts
- apps/backend/src/api/transformers/BaseTagTransformer.ts
- apps/backend/src/api/transformers/ContactTransformer.ts
Contact tags were previously only visible to admins, but since #63 have been loadable for the contact themselves too (e.g. via `/contact/me`). This PR re-introduces the admin only permission
This PR also re-enables logging response validation problems as errors rather than notices so we can see these problems more readily.
In general, this points to us needing to have a bigger conversation about how we are enforcing permissions and access as it's a bit all over the place at the moment and easy to make mistakes.
> fix: only load contact tags for admins

- apps/frontend/src/components/pages/admin/contacts/contacts.interface.ts
- packages/common/src/search/contacts.ts
- packages/core/src/filter-handlers/contact.filter-handlers.ts
- packages/core/src/type/filter-handlers.ts
- packages/locale/src/locales/de.json
- packages/locale/src/locales/de@informal.json
- packages/locale/src/locales/en.json
- packages/vue/src/components/form/AppRadioGroup.vue
- packages/vue/src/components/form/AppRadioInput.vue
Adds a filter which checks if the user has set a password on their account, which is how we define a user as being active.
Also fixes a bug with `AppRadioInput` where it wouldn't allow `false` as a valid value (via `value || null`). Using `defineModel` is clearer in any case and removes this problem.
```vue
<template>
<AppRadioInput v-model="myVal" :value="false" /> 
<AppRadioGroup
v-model="myVal"
:options="[
[false, 'Selected no'], 
[true, 'Selected yes']
]"
/> 
</template>
<script setup>
const myVal = ref(false)
</script>
```
> feat: add active user filter

- packages/client/src/api/callout-reviewer.client.ts
The `CalloutReviewerClient` should delegate `contact` deserializing to `ContactClient`. This bug was manifesting as `contact.displayName` being undefined for reviewers
> fix: reviewer displayName is undefined

- .env.test
I use `.env` to `BEABEE_DATABASE_URL` to switch between different database, e.g. when I want a fresh database or am working with migrations. This causes the tests to fail because they expect the database credentials to be the main DB credentials.
This PR adds an override to `.env.test` to force that to be true in the testing environment.
> test: database credentials are hardcoded for tests

- apps/backend/src/api/interceptors/ValidateResponseInterceptor.ts
This is creating loads of error emails and isn't treated as an error at the moment. Downgrade it to a warning for now.
> chore: convert error to warning

- apps/backend/src/api/controllers/CalloutController.ts
- apps/backend/src/api/dto/CalloutResponseDto.ts
- apps/frontend/src/components/pages/callouts/CalloutThanksBox.vue
- packages/client/src/api/callout.client.ts
- packages/client/test/api/callout.test.ts
- packages/common/src/types/create-callout-response-data.ts
- packages/core/src/lib/passport.ts
- packages/core/src/logging.ts
- packages/core/src/server.ts
- packages/core/src/services/CalloutsService.ts
- packages/core/src/services/NewsletterService.ts
- packages/locale/src/locales/de.json
- packages/locale/src/locales/de@easy.json
- packages/locale/src/locales/de@informal.json
- packages/locale/src/locales/en.json
- packages/locale/src/locales/it.json
- packages/locale/src/locales/nl.json
- packages/locale/src/locales/pt.json
- packages/locale/src/locales/ru.json
- packages/vue/src/components/notification/AppNotification.vue
This PR suppresses errors that occur when a guest response is converted into a contact response. This prevents the endpoint from being used to probe if a particular contact has responded to a callout. The guest will always see success, regardless of whether the response has really been stored or not.
The create callout response endpoint has therefore changed for non-logged in users (guests). When guests creates a response they are only given back the ID of the response, which could be randomly generated nonsense if the response wasn't created.
Logged in users:
```
POST /callout/slug/responses
Cookie: <as logged in user>
<response DTO>
```
Guests:
```
POST /callout/slug/responses
{"id": "xxx"}
```
> feat: suppress some response errors for guest submissions

- apps/frontend/src/components/pages/admin/callouts/tabs/SettingsTab.vue
- apps/frontend/src/utils/callouts.ts
This PR fixes two problems with Captcha settings:
* Captcha settings should be visible in CNR mode
* New callouts should default to no Captcha (not all clients have Captcha functionality in any case, they need a Captchafox key)
> fix: Captcha settings

- packages/core/src/config/env.ts
A config value can now be preceded with `base64:` to indicate that it is base64 encoded. This allows.
This gives us a way to work around a limitation in the cron service, which handles environment variables differently to other environments. The cron environment [can't handle environment variables](https://unix.stackexchange.com/questions/542458/cron-is-truncating-environment-variables-containing-a-hash) with a hash (#) in the value, instead they get passed as a comment.
```sh
BEABEE_EMAIL_SETTINGS_USER_PASS="123#123"
```
This value would be `123#123` in most services, but `123` in the cron daemon :disappointed:. This was very annoying to track down!
Now we can store this value as
```sh
BEABEE_EMAIL_SETTINGS_USER_PASS="base64:MTIzIzEyMw=="
```
And it will work everywhere :tada:
> feat: optionally base64 encode config values

- packages/core/src/utils/rules.ts
This is currently throwing an internal server error, but is really a problem with the API request (so a bad request error)
Generally this error occurs when an API call is made with a `contact == "me"` filter, but the caller isn't authenticated in so "me" can't be mapped to a contact.
> chore: throw non 500 error for API requests with unmappable contact

- apps/backend/src/tools/process-segments.ts
This cleans up a bit of logging noise where a segment with invalid rules throws an error that should be a warning in a cronjob
> fix: catch invalid rule errors as warnings

- apps/minio/Dockerfile
- apps/minio/init-bucket.sh
- packages/core/src/services/DocumentService.ts
- packages/core/src/utils/file.ts
This PR improves file extension handling for document uploads and refines the MinIO Docker healthcheck. The changes ensure that file extensions are consistently prefixed with a dot (e.g., `.pdf` instead of `pdf`), which resolves issues with file naming and mimetype detection. Additionally, the MinIO Docker healthcheck is updated to include a start period, and the default bucket is no longer made public by default.
- **`getExtensionFromMimetype`** in `packages/core/src/utils/file.ts` now always returns extensions with a leading dot (e.g., `.pdf`, `.jpg`).
- **`getMimetypeFromExtension`** is updated to handle extensions with or without a leading dot.
- **`DocumentService.uploadDocument`** in `packages/core/src/services/DocumentService.ts` now uses the new extension format, ensuring uploaded …
> Fix MinIO healthcheck and file extension handling for document uploads

- apps/backend-cli/src/actions/migrate-uploads/migrate-uploads.ts
- apps/backend-cli/src/commands/migrate-uploads.ts
- apps/backend-cli/src/types/migrate-uploads.ts
- apps/minio/init-bucket.sh
- Modified the migration logic to process both document and image uploads from callout responses.
- Updated function names and comments for clarity, reflecting the new handling of file types.
- Adjusted command options and type definitions to use "calloutResponseFiles" instead of "calloutResponseDocuments".
- Improved the initialization script for MinIO to actively check for service availability instead of using a fixed sleep duration.
> fix(migrate-uploads): Update migration process to handle both documents and images

- apps/backend-cli/src/actions/migrate-uploads/migrate-uploads.ts
- packages/core/src/services/CalloutsService.ts
- Modified the `processFileUpload` function to make `calloutId` optional in the response parameter.
- Adjusted the `CalloutsService` to select only the `id` and `answers` fields from the callout responses, removing the `calloutId` from the selection.
> fix(migrate-uploads): Update response structure for file uploads

- apps/backend-cli/src/actions/migrate-uploads/migrate-uploads.ts
- packages/common/src/utils/callouts.ts
- Updated the `processCalloutResponseDocuments` function to log a warning for unsupported file formats instead of processing them.
- Enhanced the `isFormioFileAnswer` utility to accommodate older file structures by making certain properties optional.
- This change improves the robustness of the upload migration process by ensuring only valid file formats are processed.
> fix(migrate-uploads): Enhanced the `isFormioFileAnswer` utility to

- apps/frontend/src/components/pages/callouts/CalloutIntroPanel.vue
Hotfix for:
```
When you go to i.e. https://achtungbarriere.crowdnewsroom.org/callouts/wo-kommst-du-nicht-voran/map,
on the left hand side you have text and a picture popping up explaining what the site is all about.
* The pictures on achtungbarriere as well as on [abriss-atlas.ch](http://abriss-atlas.ch/) are no longer visible.
```
> feat(frontend): Update CalloutIntroPanel to use correct callout image URL

- apps/frontend/src/components/pages/callouts/CalloutShowResponsePanel.vue
- apps/frontend/src/pages/callouts/[id]/gallery.vue
When I click on an image on https://abriss-atlas.ch/gallery/ a transparent mask appears, but nothing else.
The problem was that the panel was looking for response number 0, but real responses have IDs like 123, 456. We fixed this by making `currentResponseNumber` a required prop and having the parent component pass the correct response number directly.
- Made `currentResponseNumber` a required prop in `CalloutShowResponsePanel` instead of using complex fallback logic
- Updated gallery.vue to pass the selected response number explicitly to the panel component
- Updated image handling in gallery.vue and CalloutIntroPanel.vue to use `resolveImageUrl` utility for consistent image URL resolution
> fix(frontend): Gallery response panel not showing when clicking images

- .env.example
- docker-compose.yml
Now that all files should have been migrated on most instances, we no longer need the Docker migration service, so I have removed it. For the remaining instances, we can start the migration by hand with `yarn backend-cli migrate-uploads --source=/old_data`.
> chore: Remove file upload migration docker service

- apps/backend/src/api/controllers/CalloutController.ts
- apps/frontend/src/utils/callouts.ts
- packages/client/test/api/data/callouts.ts
- packages/common/src/types/create-callout-data.ts
- packages/common/src/types/create-callout-variant-data.ts
- packages/common/src/types/index.ts
- packages/common/src/types/update-callout-data.ts
- packages/core/src/services/CalloutsService.ts
This PR comes from starting to write a test for the reviewers changes and noticing that `createMinimalTestCallout` had an [empty `variants` value](https://github.com/beabee-communityrm/monorepo/compare/refactor/enforce-default-variant?expand=1#diff-06297c2672011189124e7161c66dba50dbe5e68901529f87bc9e382ed46b5b24L132). Callouts always need a default variant. This PR enforces this requirement more strictly with types.
It looks like `createMinimalTestCallout` isn't actually being used at the moment, but it would have thrown an error if it was used.
> refactor: enforce that callout.variants.default must exist on creation

- packages/test-utils/vitest/docker-compose-setup.ts
The tests are failing locally for me and have also started failing [here](https://github.com/beabee-communityrm/monorepo/actions/runs/16163549539/job/45619996255#step:4:400) for the same reason.
```
[@beabee/e2e-api-tests]:  Container beabee-test-frontend-1  Creating
[@beabee/e2e-api-tests]:  Container beabee-test-frontend-1  Error response from daemon: No such image: beabee-test-frontend:latest
[@beabee/e2e-api-tests]: Error response from daemon: No such image: beabee-test-frontend:latest
```
The Docker test environment tries to start a subset of services (presumably for efficiency?), but by booting `app_router` it actually implicitly includes the `frontend` because the former depends on the latter. For some reason on some machines the `beabee-test-frontend` image is built , but on …
> test: start all services for tests

- packages/core/src/services/CalloutsService.ts
The `listResponsesWithFileUploads()` method in `CalloutsService` had a critical logic flaw that caused it to return far fewer responses than expected. When processing callout responses during file upload migration, only 1 response was found on fussball.correctiv.org despite many more containing file uploads.
**Root Cause:** The filter function used `return false` when encountering empty slides or components, which **rejected the entire response** instead of just skipping the empty item.
- **Fixed filter logic**: Changed `return false` to `continue` to skip only empty slides/components
- **Added missing field**: Include `calloutId` in SQL select query to match return type signature  
**Before:**
```javascript
if (!slideAnswers) return false; // ❌ Skips entire response
if (!answer) return …
```
> fix: Critical loop logic bug in CalloutResponse file upload detection

- packages/locale/README.md
Updated the README with information about translation levels and some useful links (e.g. to find missing translations in Weblate)
> chore: updated README with information translation levels

- apps/frontend/src/components/pages/callouts/CalloutForm.vue
This pull request integrates the logic from the edit response mode into the display response mode. As a result, any slides that were skipped during the survey will not be shown in the responses. This change ensures a clear distinction between default values and the actual answers provided by users.
> feat: fix conditional logic in response display

- apps/webhooks/src/handlers/mailchimp.ts
- packages/core/src/lib/mailchimp.ts
- packages/core/src/services/NewsletterService.ts
- packages/core/src/type/mc-status.ts
Archived was added as a status at some point. In general we should provide a fallback and send ourselves an alert when we detect an unknown status as this could indicate a change in Mailchimp's API.
> fix: handle Mailchimp archived status and add fallback for new statuses

- packages/locale/src/locales/de.json
- packages/locale/src/locales/de@easy.json
- packages/locale/src/locales/de@informal.json
- packages/locale/src/locales/el.json
- packages/locale/src/locales/en.json
- packages/locale/src/locales/fr.json
- packages/locale/src/locales/it.json
- packages/locale/src/locales/nl.json
- packages/locale/src/locales/pt.json
- packages/locale/src/locales/ru.json
- packages/locale/src/template.json
This PR adds missing labels for response links in callout footer settings.
> fix(locale): add missing labels

- .cursor/rules/git-commit-best-practices.mdc
**Problem**: AI tools were making commits automatically without developer review, leading to potential quality and control issues.
**Solution**: Updated `.cursor/rules/git-commit-best-practices.mdc` to require explicit developer approval before any commits.
- ⚠️ **New Policy**: AI must ask for approval before committing
- 📋 **Review Process**: Show planned commit message and changes first  
- 🔒 **Developer Control**: Only commit when explicitly instructed
Learning from experience with excessive AI automation in [PR #267](https://github.com/beabee-communityrm/monorepo/pull/267) - maintaining developer oversight while keeping AI assistance benefits.
**Impact**: Prevents unreviewed commits, maintains code quality standards.
> feat(cursor): Add Developer Approval Requirement for AI Commits
